<?php

/**
 * ربط أسماء المسارات بصلاحيات slug (يجب أن تطابق سجلات permissions بعد التشغيل).
 */
return [
    'login' => 'login',
    'logout' => 'logout',

    'home' => 'home',

    'projects.index' => 'projects.index',
    'projects.store' => 'projects.store',
    'projects.edit' => 'projects.edit',
    'projects.contract-template' => 'projects.contract-template',
    'projects.update' => 'projects.update',
    'projects.adopt-plan' => 'projects.update',
    'projects.destroy' => 'projects.destroy',
    'projects.draft' => 'projects.draft',
    'projects.restore' => 'projects.restore',

    'projects.landing' => 'projects.landing',

    'dashboard' => 'dashboard',

    'properties.index' => 'properties.index',
    'properties.show' => 'properties.show',
    'properties.create' => 'properties.create',
    'properties.store' => 'properties.store',
    'properties.edit' => 'properties.edit',
    'properties.update' => 'properties.update',
    'properties.destroy' => 'properties.destroy',

    'areas.index' => 'areas.index',
    'areas.create' => 'areas.create',
    'areas.store' => 'areas.store',
    'areas.edit' => 'areas.edit',
    'areas.update' => 'areas.update',
    'areas.destroy' => 'areas.destroy',

    'facings.index' => 'facings.index',
    'facings.create' => 'facings.create',
    'facings.store' => 'facings.store',
    'facings.edit' => 'facings.edit',
    'facings.update' => 'facings.update',
    'facings.destroy' => 'facings.destroy',

    'expense-types.index' => 'expense-types.index',
    'expense-types.create' => 'expense-types.create',
    'expense-types.store' => 'expense-types.store',
    'expense-types.edit' => 'expense-types.edit',
    'expense-types.update' => 'expense-types.update',
    'expense-types.destroy' => 'expense-types.destroy',

    'lands.index' => 'lands.index',
    'lands.create' => 'lands.create',
    'lands.store' => 'lands.store',
    'lands.edit' => 'lands.edit',
    'lands.update' => 'lands.update',
    'lands.destroy' => 'lands.destroy',

    'shareholders.index' => 'shareholders.index',
    'shareholders.show' => 'shareholders.show',
    'shareholders.create' => 'shareholders.create',
    'shareholders.store' => 'shareholders.store',
    'shareholders.edit' => 'shareholders.edit',
    'shareholders.update' => 'shareholders.update',
    'shareholders.destroy' => 'shareholders.destroy',
    'shareholders.ledger.store' => 'shareholders.manage',
    'shareholders.ledger.destroy' => 'shareholders.manage',
    'shareholders.projects.attach' => 'shareholders.manage',
    'shareholders.lands.attach' => 'shareholders.manage',
    'shareholders.funding.update' => 'shareholders.manage',

    'sales.index' => 'sales.index',
    'sales.show' => 'sales.show',
    'sales.create' => 'sales.create',
    'sales.store' => 'sales.store',
    'sales.edit' => 'sales.edit',
    'sales.update' => 'sales.update',
    'sales.destroy' => 'sales.destroy',

    'clients.index' => 'clients.index',
    'clients.show' => 'clients.show',

    'contracts.index' => 'contracts.index',
    'contracts.show' => 'contracts.show',
    'contracts.word' => 'contracts.word',

    'revenues.index' => 'revenues.index',
    'revenues.show' => 'revenues.show',
    'revenues.create' => 'revenues.create',
    'revenues.store' => 'revenues.store',
    'revenues.edit' => 'revenues.edit',
    'revenues.update' => 'revenues.update',
    'revenues.destroy' => 'revenues.destroy',

    'expenses.index' => 'expenses.index',
    'expenses.show' => 'expenses.show',
    'expenses.create' => 'expenses.create',
    'expenses.store' => 'expenses.store',
    'expenses.edit' => 'expenses.edit',
    'expenses.update' => 'expenses.update',
    'expenses.destroy' => 'expenses.destroy',

    'cashbox.index' => 'cashbox.index',
    'cashbox.store' => 'cashbox.store',
    'global-cashbox.index' => 'cashbox.view',
    'land-cashbox.index' => 'cashbox.view',
    'land-cashbox.store' => 'cashbox.manage',
    'fund-transfers.index' => 'cashbox.view',
    'fund-transfers.store' => 'cashbox.manage',

    'approvals.index' => 'approvals.index',
    'approvals.approve' => 'approvals.approve',
    'approvals.reject' => 'approvals.reject',

    'debts.index' => 'debts.index',
    'debts.create' => 'debts.create',
    'debts.store' => 'debts.store',
    'debts.edit' => 'debts.edit',
    'debts.update' => 'debts.update',
    'debts.destroy' => 'debts.destroy',
    'debts.pay-from-cashbox' => 'debts.pay-from-cashbox',

    'remaining.index' => 'remaining.index',

    'settlements.index' => 'settlements.index',

    'reports.index' => 'reports.index',
    'reports.export' => 'reports.export',
    'reports.export-excel' => 'reports.export',
    'reports.export-pdf' => 'reports.export',
    'reports.export_excel' => 'reports.export',
    'reports.export_pdf' => 'reports.export',

    'settings.edit' => 'settings.edit',
    'settings.update' => 'settings.update',
    'settings.send-available-units-report' => 'settings.send-available-units-report',

    'crm-leads.index' => 'crm-leads.index',
    'crm-leads.create' => 'crm-leads.create',
    'crm-leads.store' => 'crm-leads.store',
    'crm-leads.show' => 'crm-leads.show',
    'crm-leads.edit' => 'crm-leads.edit',
    'crm-leads.update' => 'crm-leads.update',
    'crm-leads.destroy' => 'crm-leads.destroy',
    'crm-leads.activities.store' => 'crm-leads.activities.store',

    'land-trading.index' => 'land-trading.index',
    'land-trading.sales' => 'land-trading.view',
    'land-trading.create' => 'land-trading.create',
    'land-trading.store' => 'land-trading.store',
    'land-trading.show' => 'land-trading.show',
    'land-trading.edit' => 'land-trading.edit',
    'land-trading.update' => 'land-trading.update',
    'land-trading.destroy' => 'land-trading.destroy',
    'land-trading.payments.store' => 'land-trading.manage',
    'land-trading.payments.distribute' => 'land-trading.manage',
    'land-trading.payments.destroy' => 'land-trading.manage',
    'land-trading.adopt-plan' => 'land-trading.manage',
    'land-trading.parts.store' => 'land-trading.manage',
    'land-trading.parts.update' => 'land-trading.manage',
    'land-trading.parts.destroy' => 'land-trading.manage',

    'tasks.index' => 'tasks.index',
    'tasks.mine' => 'tasks.view',
    'tasks.create' => 'tasks.create',
    'tasks.store' => 'tasks.store',
    'tasks.show' => 'tasks.show',
    'tasks.edit' => 'tasks.manage',
    'tasks.update' => 'tasks.update',
    'tasks.destroy' => 'tasks.destroy',
    'tasks.updates.store' => 'tasks.updates.store',
    'tasks.updates.attachment' => 'tasks.view',

    'site-sketch.index' => 'site-sketch.view',
    'site-sketch.cells.update' => 'site-sketch.manage',
    'site-sketch.reset' => 'site-sketch.manage',

    'users.index' => 'users.index',
    'users.create' => 'users.create',
    'users.store' => 'users.store',
    'users.edit' => 'users.edit',
    'users.update' => 'users.update',
    'users.destroy' => 'users.destroy',

    'activity-log.index' => 'activity-log.index',

    'storage.local' => 'storage.local',
    'storage.local.upload' => 'storage.local.upload',
];
